[build]
  # Directorio base donde está el frontend
  base = "frontend"
  
  # Comando de construcción
  command = "npm run build"
  
  # Directorio de publicación (donde se genera el build)
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"
  
  # Variables de entorno para producción
  VITE_API_BASE_URL = "https://tu-backend-en-render.onrender.com"
  VITE_BACKEND_URL = "https://tu-backend-en-render.onrender.com"
  NODE_ENV = "production"
  VITE_NODE_ENV = "production"
  VITE_DEBUG_MODE = "false"
  VITE_API_TIMEOUT = "10000"

# Configuración de redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
