[build]
  # Directorio base donde está el frontend
  base = "frontend"
  
  # Comando de construcción
  command = "npm run build"
  
  # Directorio de publicación (donde se genera el build)
  publish = "dist"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "18"

# Configuración de redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
